---
- name: Check System State Before Managing Target
  include_tasks:
    file: check_system_state.yml
    apply:
      tags:
        - always
        - truenas_check_system_state
  tags:
    - always
    - truenas_check_system_state

- name: Manage Mail Service Configuration
  include_tasks:
    file: mail.yml
    apply:
      tags:
        - truenas_mail
  tags:
    - truenas_mail

- name: Manage System General Service Configuration
  include_tasks:
    file: system_general.yml
    apply:
      tags:
        - truenas_system
        - truenas_system_general
  tags:
    - truenas_system
    - truenas_system_general

- name: Manage System Advanced Service Configuration
  include_tasks:
    file: system_advanced.yml
    apply:
      tags:
        - truenas_system
        - truenas_system_advanced
  tags:
    - truenas_system
    - truenas_system_advanced
