---
- name: Check System State Before Managing Target
  include_tasks:
    file: check_system_state.yml
    apply:
      tags:
        - always
        - truenas_check_system_state
  tags:
    - always
    - truenas_check_system_state

- name: Manage Network Configuration
  include_tasks:
    file: network_configuration.yml
    apply:
      tags:
        - truenas_network_configuration
  tags:
    - truenas_network_configuration

- name: Manage Interface Configuration
  include_tasks:
    file: interface.yml
    apply:
      tags:
        - truenas_interface
  tags:
    - truenas_interface

- name: Manage Groups
  include_tasks:
    file: group.yml
    apply:
      tags:
        - truenas_group
  tags:
    - truenas_group

- name: Manage Users
  include_tasks:
    file: user.yml
    apply:
      tags:
        - truenas_user
  tags:
    - truenas_user

- name: Manage Mail Service Configuration
  include_tasks:
    file: mail.yml
    apply:
      tags:
        - truenas_mail
  tags:
    - truenas_mail

- name: Manage System General Service Configuration
  include_tasks:
    file: system_general.yml
    apply:
      tags:
        - truenas_system
        - truenas_system_general
  tags:
    - truenas_system
    - truenas_system_general

- name: Manage System Advanced Service Configuration
  include_tasks:
    file: system_advanced.yml
    apply:
      tags:
        - truenas_system
        - truenas_system_advanced
  tags:
    - truenas_system
    - truenas_system_advanced

- name: Manage System NTP Server Configuration
  include_tasks:
    file: system_ntpserver.yml
    apply:
      tags:
        - truenas_system
        - truenas_system_ntpserver
  tags:
    - truenas_system
    - truenas_system_ntpserver

- name: Manage Alertservice Configuration
  include_tasks:
    file: alertservice.yml
    apply:
      tags:
        - truenas_alertservice
  tags:
    - truenas_alertservice
  when: truenas_config_alertservice is defined

- name: Manage Service Configuration
  include_tasks:
    file: service.yml
    apply:
      tags:
        - truenas_service
  tags:
    - truenas_service
  when: truenas_config_service is defined

- name: Manage ActiveDirectory Configuration
  include_tasks:
    file: activedirectory.yml
    apply:
      tags:
        - truenas_activedirectory
  tags:
    - truenas_activedirectory

- name: Manage ID Map Configuration
  include_tasks:
    file: idmap.yml
    apply:
      tags:
        - truenas_idmap
  tags:
    - truenas_idmap

- name: Manage Cronjob Configuration
  include_tasks:
    file: cronjob.yml
    apply:
      tags:
        - truenas_cronjob
  tags:
    - truenas_cronjob

- name: Manage Pool Dataset Configuration
  include_tasks:
    file: pool_dataset.yml
    apply:
      tags:
        - truenas_pool_dataset
  tags:
    - truenas_pool_dataset

- name: Manage Pool Snapshot Task Configuration
  include_tasks:
    file: pool_snapshottask.yml
    apply:
      tags:
        - truenas_pool_snapshottask
  tags:
    - truenas_pool_snapshottask

- name: Manage Sharing NFS Configuration
  include_tasks:
    file: sharing_nfs.yml
    apply:
      tags:
        - truenas_sharing_nfs
  tags:
    - truenas_sharing_nfs

- name: Manage Sharing SMB Configuration
  include_tasks:
    file: sharing_smb.yml
    apply:
      tags:
        - truenas_sharing_smb
  tags:
    - truenas_sharing_smb

- name: Manage ZFS Replication
  include_tasks:
    file: replication.yml
    apply:
      tags:
        - truenas_replication
  tags:
    - truenas_replication

- name: Manage rsync tasks
  include_tasks:
    file: rsynctask.yml
    apply:
      tags:
        - truenas_rsynctask
  tags:
    - truenas_rsynctask
