---
- name: Check System State Before Managing Target
  include_tasks:
    file: check_system_state.yml
    apply:
      tags:
        - always
        - truenas_check_system_state
  tags:
    - always
    - truenas_check_system_state

- name: Manage Mail Service Configuration
  include_tasks:
    file: mail.yml
    apply:
      tags:
        - truenas_mail
  tags:
    - truenas_mail
