---
- name: Check System State Before Managing Target
  include_tasks:
    file: check_system_state.yml
    apply:
      tags:
        - always
        - truenas_check_system_state
  tags:
    - always
    - truenas_check_system_state

- name: Manage Network Configuration
  include_tasks:
    file: network_configuration.yml
    apply:
      tags:
        - truenas_network_configuration
  tags:
    - truenas_network_configuration

- name: Manage Interface Configuration
  include_tasks:
    file: interface.yml
    apply:
      tags:
        - truenas_interface
  tags:
    - truenas_interface

- name: Manage Groups
  include_tasks:
    file: group.yml
    apply:
      tags:
        - truenas_group
  tags:
    - truenas_group

- name: Manage Users
  include_tasks:
    file: user.yml
    apply:
      tags:
        - truenas_user
  tags:
    - truenas_user

- name: Manage Mail Service Configuration
  include_tasks:
    file: mail.yml
    apply:
      tags:
        - truenas_mail
  tags:
    - truenas_mail

- name: Manage System General Service Configuration
  include_tasks:
    file: system_general.yml
    apply:
      tags:
        - truenas_system
        - truenas_system_general
  tags:
    - truenas_system
    - truenas_system_general

- name: Manage System Advanced Service Configuration
  include_tasks:
    file: system_advanced.yml
    apply:
      tags:
        - truenas_system
        - truenas_system_advanced
  tags:
    - truenas_system
    - truenas_system_advanced
